name: talkgpt
description: TalkGPT - مساعد ذكي بالعربية
publish_to: 'none'
version: 15.0.0+15

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  path_provider: ^2.1.1
  image_picker: ^1.0.7
  crypto: ^3.0.3
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  flutter_markdown: ^0.7.4+3
  google_fonts: ^6.2.1
  local_auth: ^2.3.0
  http: ^1.2.0
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#0E1116"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
