name: talkgpt
description: TalkGPT - مساعد ذكي بالعربية
publish_to: 'none'
version: 10.0.0+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  path_provider: ^2.1.1
  image_picker: ^1.0.7
  crypto: ^3.0.3
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  flutter_markdown: ^0.7.4+3
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
